openapi: 3.2.0
info:
  title: Certificate Manager - SaaS Certificate Auto-renewal…
  version: '1.0'
servers:
- description: US Region
  url: https://api.venafi.cloud
- description: EU Region
  url: https://api.eu.venafi.cloud
- description: AU Region
  url: https://api.au.venafi.cloud
- description: UK Region
  url: https://api.uk.venafi.cloud
- description: SG Region
  url: https://api.sg.venafi.cloud
- description: CA Region
  url: https://api.ca.venafi.cloud
tags:
- name: Certificate Auto-renewal Monitoring
paths:
  /v1/autorenewal/tenantconfiguration:
    get:
      description: Retrieve the certificate expiration monitoring configuration for the current tenant
      operationId: get-v1-tenant-renewal-configuration
      responses:
        '200':
          content:
            application/json:
              example:
                id: 12a05220-4352-11ee-ac28-c1379e5decf9
                renewalWindow:
                  days: 30
              schema:
                $ref: '#/components/schemas/TenantRenewalConfiguration'
          description: Success
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
      security:
      - tppl-api-key: []
      summary: Retrieve the monitoring configuration
      tags:
      - Certificate Auto-renewal Monitoring
      x-rbac:
        permissions:
          access_type: read
          description: Ability to get the monitoring configuration
          name: ngts.autorenewal_tenantconfiguration.get
        roles:
        - PKIAdmin
        - PlatformAdmin
        - ResourceOwner
        - Guest
    put:
      description: Update the certificate expiration monitoring configuration for the current tenant
      operationId: put-v1-tenant-renewal-configuration
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantRenewalConfiguration'
        description: The options to apply
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantRenewalConfiguration'
          description: Success. The tenant configuration was successfully updated.
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
      security:
      - tppl-api-key: []
      summary: Update the monitoring configuration
      tags:
      - Certificate Auto-renewal Monitoring
      x-rbac:
        permissions:
          access_type: write
          description: Ability to update the monitoring configuration
          name: ngts.autorenewal_tenantconfiguration.update
        roles:
        - PKIAdmin
  /v1/autorenewal/trigger:
    post:
      description: The certificate renewal check is normally scheduled to run daily. This operation attempts to start the process for the current tenant now.
      operationId: post-v1-run-autorenewal
      responses:
        '200':
          content:
            application/json:
              examples:
                status:
                  $ref: '#/components/examples/StatusResponseExample'
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success. The auto-renewal check process was triggered.
      security:
      - tppl-api-key: []
      summary: Attempt to initiate the certificate renewal check process now
      tags:
      - Certificate Auto-renewal Monitoring
      x-rbac:
        permissions:
          access_type: write
          description: Ability to initiate the certificate renewal check process now
          name: ngts.autorenewal.trigger
        roles:
        - PKIAdmin
  /v1/autorenewal/status:
    get:
      description: Get details about the status of the certificate auto-renewal monitoring process.
      operationId: get-v1-status
      responses:
        '200':
          content:
            application/json:
              examples:
                status:
                  $ref: '#/components/examples/StatusResponseExample'
              schema:
                $ref: '#/components/schemas/StatusResponse'
          description: Success
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
      security:
      - tppl-api-key: []
      summary: Get the current certificate auto-renewal monitoring status
      tags:
      - Certificate Auto-renewal Monitoring
      x-rbac:
        permissions:
          access_type: read
          description: Ability to get the current certificate auto-renewal monitoring status
          name: ngts.autorenewal_status.get
        roles:
        - PKIAdmin
  /v1/autorenewal/{application_id}/configuration:
    get:
      description: Retrieve the certificate expiration monitoring configuration for the specified application
      operationId: get-v1-application-renewal-configuration
      parameters:
      - description: The ID of the application that you would like to retrieve configuration for
        example: 22153ae0-4352-11ee-b95c-3531a284802b
        in: path
        name: application_id
        required: true
        schema:
          format: UUID
          type: string
      responses:
        '200':
          content:
            application/json:
              examples:
                defaults:
                  $ref: '#/components/examples/ApplicationRenewalConfigurationExampleDefault'
                modified:
                  $ref: '#/components/examples/ApplicationRenewalConfigurationExampleModified'
              schema:
                $ref: '#/components/schemas/ApplicationRenewalConfiguration'
          description: Success
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
      security:
      - tppl-api-key: []
      summary: Retrieve the monitoring configuration
      tags:
      - Certificate Auto-renewal Monitoring
      x-rbac:
        cm-only: true
        permissions:
          access_type: read
          description: Ability to get the application monitoring configuration
          name: ngts.autorenewal_application_configuration.get
        roles:
        - PKIAdmin
        - PlatformAdmin
        - ResourceOwner
        - Guest
    put:
      description: Update the certificate expiration monitoring configuration for the specified application
      operationId: put-v1-application-renewal-configuration
      parameters:
      - description: The ID of the application you want to update
        example: 22153ae0-4352-11ee-b95c-3531a284802b
        in: path
        name: application_id
        required: true
        schema:
          format: UUID
          type: string
      requestBody:
        content:
          application/json:
            examples:
              modified:
                $ref: '#/components/examples/ApplicationRenewalConfigurationExampleModified'
            schema:
              $ref: '#/components/schemas/ApplicationRenewalConfiguration'
        description: The options to apply
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationRenewalConfiguration'
          description: Success. The application configuration was successfully updated.
        '400':
          description: BadRequest
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
      security:
      - tppl-api-key: []
      summary: Update the monitoring configuration
      tags:
      - Certificate Auto-renewal Monitoring
      x-rbac:
        cm-only: true
        permissions:
          access_type: write
          description: Ability to update the application monitoring configuration
          name: ngts.autorenewal_application_configuration.update
        roles:
        - PKIAdmin
        - PlatformAdmin
        - ResourceOwner
        - Guest
components:
  examples:
    ApplicationRenewalConfigurationExampleModified:
      value:
        id: 22153ae0-4352-11ee-b95c-3531a284802b
        renewalActions:
          provision: false
          renew: true
        renewalWindow:
          days: 15
          inherit: false
    ApplicationRenewalConfigurationExampleDefault:
      value:
        id: 22153ae0-4352-11ee-b95c-3531a284802b
        renewalActions:
          provision: false
          renew: false
        renewalWindow:
          inherit: true
    StatusResponseExample:
      value:
        current:
          applications: 13
          certificates:
            eligible: 47
            renewal:
              failed: 1
              successful: 9
              triggered: 3
          state: running
          timestamp: '2023-08-25T20:59:36.688019837Z'
        previous:
          applications: 13
          certificates:
            eligible: 47
            renewal:
              failed: 1
              successful: 46
              triggered: 47
          state: complete
          timestamp: '2023-08-24T20:57:36.688019837Z'
  schemas:
    ApplicationRenewalConfiguration:
      properties:
        renewalActions:
          description: A set of options that can be used to specify the actions that should be taken when the auto-renewal process runs.
          example:
            provision: false
            renew: true
          properties:
            provision:
              description: If true, the system with attempt to provision any certificates associated with this application after a successful auto-renewal.
              type: boolean
            renew:
              description: If true, the system will attempt to renew any certificates associated with this application that are expected to expire within the configured number of days.
              type: boolean
          required:
          - renew
          - provision
          type: object
        renewalWindow:
          description: A set of options to control the time window in which auto-renewal of certificates should be attempted.
          example:
            days: 16
            inherit: false
          properties:
            days:
              description: Any certificates associated with this application that are expected to expire within the specified number of days will be acted on.
              format: int64
              minimum: 1
              type: integer
            inherit:
              description: If true, "days" value configured for this application will be ignored and the value configured at the tenant level will be used.
              type: boolean
          required:
          - inherit
          type: object
      required:
      - renewalActions
      - renewalWindow
      type: object
    TenantRenewalConfiguration:
      properties:
        defaultIssuingTemplateId:
          format: UUID
          type: string
        id:
          description: The object ID
          example: 12a05220-4352-11ee-ac28-c1379e5decf9
          format: UUID
          type: string
        renewalActions:
          description: A set of options that can be used to specify the actions that should be taken when the auto-renewal process runs.
          example:
            provision: false
            renew: true
          properties:
            provision:
              description: If true, the system with attempt to provision any certificates associated with this application after a successful auto-renewal.
              type: boolean
            renew:
              description: If true, the system will attempt to renew any certificates associated with this application that are expected to expire within the configured number of days.
              type: boolean
          required:
          - renew
          - provision
          type: object
        renewalWindow:
          description: A set of options to control the time window in which auto-renewal of certificates should be attempted.
          example:
            days: 30
          properties:
            days:
              description: Any certificates associated with this object that are expected to expire within the specified number of days will be acted on.
              format: int64
              minimum: 1
              type: integer
          required:
          - days
          type: object
      required:
      - id
      - renewalWindow
      type: object
    StatusResponse:
      description: Details about the current in-progress certificate auto-renewal process, and the most recently completed process.
      properties:
        current:
          $ref: '#/components/schemas/StatusResponseItem'
        previous:
          $ref: '#/components/schemas/StatusResponseItem'
      required:
      - current
      type: object
    StatusResponseItem:
      description: Details about the upcoming certificate auto-renewal run.
      example:
        applications: 13
        certificates:
          eligible: 47
          renewal:
            failed: 1
            successful: 9
            triggered: 3
        state: running
        timestamp: '2023-08-25T20:59:36.688019837Z'
      properties:
        applications:
          description: The number of applications that have auto-renewal enabled.
          example: 13
          format: int64
          type: integer
        certificates:
          description: A set of statistics related to the certificates that were included in the auto-renewal process.
          example:
            eligible: 47
            renewal:
              failed: 1
              successful: 9
              triggered: 3
          properties:
            eligible:
              description: The number of certificates that belong to an application that has auto-renewal enabled.
              format: int64
              type: integer
            renewal:
              properties:
                failed:
                  description: The number of certificates for which renewal failed
                  format: int64
                  type: integer
                successful:
                  description: The number of certificates for which renewal completed successfully
                  format: int64
                  type: integer
                triggered:
                  description: The number of certificates for which the renewal has been started
                  format: int64
                  type: integer
              required:
              - triggered
              - successful
              - failed
              type: object
          required:
          - eligible
          - renewal
          type: object
        state:
          description: A string representing the status of a specific run of the auto-renewal process.
          enum:
          - pending
          - triggered
          - running
          - complete
          - awaiting results
          - no enabled apps
          - no automated keypair service active
          - failure
          example: running
          type: string
        timestamp:
          description: The date and time when certificate auto-renewal is estimated to begin.
          example: '2023-08-25T20:59:36.688019837Z'
          format: date-time
          type: string
      required:
      - timestamp
      - state
      - applications
      - certificates
      type: object
  securitySchemes:
    service-account:
      in: header
      name: service-account
      type: apiKey
    tppl-api-key:
      in: header
      name: tppl-api-key
      type: apiKey
x-readme:
  samples-languages:
  - curl
  - go
  - java
  - javascript
  - node
  - python
